# Generated by Django 6.0.3 on 2026-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(),
        ),
    ]
