# Generated by Django 6.0.3 on 2026-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('contact', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.IntegerField()),
                ('ordered_quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Staff', 'Staff')]),
        ),
    ]
