# Generated by Django 6.0.3 on 2026-05-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0002_alter_sale_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medflowapp.customer'),
        ),
    ]
