# Generated by Django 6.0.3 on 2026-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0002_customers_medicines_orders_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.AddField(
            model_name='medicines',
            name='med_category',
            field=models.CharField(choices=[('TAB', 'TAB'), ('SYR', 'SYRUP'), ('CAP', 'CAP'), ('INJ', 'INJ')], default='----'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='stock_status',
            field=models.CharField(choices=[('Out of Stock', 'Out of Stock'), ('Overstock', 'Overstock')], default='Overstock'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Staff', 'Staff')]),
        ),
    ]
