# Generated by Django 6.0.3 on 2026-04-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0003_delete_customers_medicines_med_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='med_category',
            field=models.CharField(choices=[('------', '-----'), ('TAB', 'TAB'), ('SYR', 'SYRUP'), ('CAP', 'CAP'), ('INJ', 'INJ')], default='----'),
        ),
    ]
