# Generated by Django 6.0.3 on 2026-04-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0004_alter_medicines_med_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Employee',
        ),
    ]
