# Generated by Django 6.0.3 on 2026-04-14 05:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0006_employee_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField()),
                ('cost_price', models.FloatField()),
                ('purchase_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('gst_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('sale_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_contact', models.IntegerField()),
                ('supplier_person', models.CharField()),
                ('supplier_address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 14, 5, 33, 39, 893558, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='stock_status',
            field=models.CharField(choices=[('Out-of-Stock', 'Out-of-Stock'), ('In-stock', 'In-stock')], default='Overstock'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='medicine_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflowapp.medicines'),
        ),
        migrations.AddField(
            model_name='sales',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflowapp.employee'),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='medicine_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflowapp.medicines'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='supplier_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medflowapp.suppliers'),
        ),
    ]
