# Generated by Django 6.0.3 on 2026-04-15 06:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0007_purchases_sales_salesitems_suppliers_delete_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_address', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 4, 15, 6, 48, 53, 646599, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AddField(
            model_name='salesitems',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='sale_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='medflowapp.sales'),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AddField(
            model_name='salesitems',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 15, 6, 48, 53, 645253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='stock_status',
            field=models.CharField(choices=[('Out-of-Stock', 'Out-of-Stock'), ('In-stock', 'In-stock')], default='In-stock'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 15, 6, 48, 53, 650035, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 15, 6, 48, 53, 650984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
