# Generated by Django 6.0.3 on 2026-04-17 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0008_customers_salesitems_quantity_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='customer_email',
        ),
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 5, 56, 9, 299708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 5, 56, 9, 298888, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='stock_status',
            field=models.CharField(choices=[('Out-of-Stock', 'Out-of-Stock'), ('In-Stock', 'In-Stock')], default='In-stock'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 5, 56, 9, 301875, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 5, 56, 9, 302784, tzinfo=datetime.timezone.utc)),
        ),
    ]
