# Generated by Django 6.0.3 on 2026-04-18 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0009_remove_customers_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 22, 43, 370725, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 22, 43, 369890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 22, 43, 372905, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 22, 43, 373819, tzinfo=datetime.timezone.utc)),
        ),
    ]
