# Generated by Django 6.0.3 on 2026-04-18 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0010_alter_customers_created_at_alter_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 31, 3, 985101, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 31, 3, 984204, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 31, 3, 987482, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 3, 31, 3, 988478, tzinfo=datetime.timezone.utc)),
        ),
    ]
