# Generated by Django 6.0.3 on 2026-04-21 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medflowapp', '0011_alter_customers_created_at_alter_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 21, 5, 3, 28, 589043, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 21, 5, 3, 28, 586896, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 21, 5, 3, 28, 594152, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='invoice_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 21, 5, 3, 28, 595726, tzinfo=datetime.timezone.utc)),
        ),
    ]
